package goxml
/*
#cgo pkg-config: libxml-2.0
#include <libxml/HTMLparser.h>
*/
import "C"

const HTML_REQUIRED = C.HTML_REQUIRED
const HTML_PARSE_PEDANTIC = C.HTML_PARSE_PEDANTIC
const HTML_PARSE_NONET = C.HTML_PARSE_NONET
const HTML_NA = C.HTML_NA
const HTML_INVALID = C.HTML_INVALID
const HTML_PARSE_COMPACT = C.HTML_PARSE_COMPACT
const HTML_VALID = C.HTML_VALID
const HTML_PARSE_NOBLANKS = C.HTML_PARSE_NOBLANKS
const HTML_PARSE_NOWARNING = C.HTML_PARSE_NOWARNING
const HTML_DEPRECATED = C.HTML_DEPRECATED
const HTML_PARSE_NOERROR = C.HTML_PARSE_NOERROR
const HTML_PARSE_RECOVER = C.HTML_PARSE_RECOVER
const HTML_PARSE_NOIMPLIED = C.HTML_PARSE_NOIMPLIED
const HTML_PARSE_NODEFDTD = C.HTML_PARSE_NODEFDTD
